const { Regex } = require('@companion-module/base')

const { MODELS } = require('./models.js')

module.exports = {
	getConfigFields() {
		return [
			{
				type: 'static-text',
				id: 'info',
				width: 12,
				label: 'Setup Instructions',
				value:
					"<strong>Add your Canon PTZ cameras below:</strong><br/>1. Enter each camera's IP address<br/>2. Assign a camera index number (1, 2, 3, etc.)<br/>3. Select the camera model<br/>4. Configure polling interval and other settings",
			},
			{
				type: 'static-text',
				id: 'cameraListHeader',
				width: 12,
				label: 'Cameras',
				value: 'Configure up to 10 cameras below:',
			},
			{
				type: 'textinput',
				id: 'camera1_ip',
				label: 'Camera 1 IP Address',
				width: 4,
				default: '',
				tooltip: 'Leave blank to disable',
			},
			{
				type: 'textinput',
				id: 'camera1_index',
				label: 'Camera 1 Index',
				width: 2,
				default: '1',
				regex: Regex.NUMBER,
			},
			{
				type: 'textinput',
				id: 'camera2_ip',
				label: 'Camera 2 IP Address',
				width: 4,
				default: '',
				tooltip: 'Leave blank to disable',
			},
			{
				type: 'textinput',
				id: 'camera2_index',
				label: 'Camera 2 Index',
				width: 2,
				default: '2',
				regex: Regex.NUMBER,
			},
			{
				type: 'textinput',
				id: 'camera3_ip',
				label: 'Camera 3 IP Address',
				width: 4,
				default: '',
				tooltip: 'Leave blank to disable',
			},
			{
				type: 'textinput',
				id: 'camera3_index',
				label: 'Camera 3 Index',
				width: 2,
				default: '3',
				regex: Regex.NUMBER,
			},
			{
				type: 'textinput',
				id: 'camera4_ip',
				label: 'Camera 4 IP Address',
				width: 4,
				default: '',
				tooltip: 'Leave blank to disable',
			},
			{
				type: 'textinput',
				id: 'camera4_index',
				label: 'Camera 4 Index',
				width: 2,
				default: '4',
				regex: Regex.NUMBER,
			},
			{
				type: 'textinput',
				id: 'camera5_ip',
				label: 'Camera 5 IP Address',
				width: 4,
				default: '',
				tooltip: 'Leave blank to disable',
			},
			{
				type: 'textinput',
				id: 'camera5_index',
				label: 'Camera 5 Index',
				width: 2,
				default: '5',
				regex: Regex.NUMBER,
			},
			{
				type: 'textinput',
				id: 'camera6_ip',
				label: 'Camera 6 IP Address',
				width: 4,
				default: '',
				tooltip: 'Leave blank to disable',
			},
			{
				type: 'textinput',
				id: 'camera6_index',
				label: 'Camera 6 Index',
				width: 2,
				default: '6',
				regex: Regex.NUMBER,
			},
			{
				type: 'textinput',
				id: 'camera7_ip',
				label: 'Camera 7 IP Address',
				width: 4,
				default: '',
				tooltip: 'Leave blank to disable',
			},
			{
				type: 'textinput',
				id: 'camera7_index',
				label: 'Camera 7 Index',
				width: 2,
				default: '7',
				regex: Regex.NUMBER,
			},
			{
				type: 'textinput',
				id: 'camera8_ip',
				label: 'Camera 8 IP Address',
				width: 4,
				default: '',
				tooltip: 'Leave blank to disable',
			},
			{
				type: 'textinput',
				id: 'camera8_index',
				label: 'Camera 8 Index',
				width: 2,
				default: '8',
				regex: Regex.NUMBER,
			},
			{
				type: 'textinput',
				id: 'camera9_ip',
				label: 'Camera 9 IP Address',
				width: 4,
				default: '',
				tooltip: 'Leave blank to disable',
			},
			{
				type: 'textinput',
				id: 'camera9_index',
				label: 'Camera 9 Index',
				width: 2,
				default: '9',
				regex: Regex.NUMBER,
			},
			{
				type: 'textinput',
				id: 'camera10_ip',
				label: 'Camera 10 IP Address',
				width: 4,
				default: '',
				tooltip: 'Leave blank to disable',
			},
			{
				type: 'textinput',
				id: 'camera10_index',
				label: 'Camera 10 Index',
				width: 2,
				default: '10',
				regex: Regex.NUMBER,
			},
			{
				type: 'static-text',
				id: 'dummy0',
				width: 12,
				label: ' ',
				value: ' ',
			},
			{
				type: 'textinput',
				id: 'httpPort',
				label: 'HTTP Port (Default: 80)',
				width: 3,
				default: '80',
				regex: Regex.PORT,
			},
			{
				type: 'static-text',
				id: 'dummy1',
				width: 12,
				label: ' ',
				value: ' ',
			},
			{
				type: 'static-text',
				id: 'modelInfo',
				width: 12,
				label: 'Camera Model',
				value: 'Please Select the camera model.',
			},
			{
				type: 'dropdown',
				id: 'model',
				label: 'Select Your Camera Model',
				width: 6,
				default: MODELS[0].id,
				choices: MODELS,
				minChoicesForSearch: 5,
			},
			{
				type: 'static-text',
				id: 'intervalInfo',
				width: 12,
				label: 'Update Interval',
				value:
					'Please enter the amount of time in milliseconds to request new information from the camera. Set to 0 to disable.',
			},
			{
				type: 'textinput',
				id: 'interval',
				label: 'Update Interval',
				width: 3,
				default: 5000,
			},
			{
				type: 'checkbox',
				id: 'continuePolling',
				label: 'Continue Polling even in error state',
				width: 3,
				default: false,
				isVisible: (configValues) => configValues.interval > 0,
			},
			{
				type: 'static-text',
				id: 'dummy2',
				width: 12,
				label: ' ',
				value: ' ',
			},
			{
				type: 'textinput',
				id: 'username',
				label: 'Camera Username (optional)',
				width: 6,
				default: '',
			},
			{
				type: 'password',
				id: 'password',
				label: 'Camera Password (optional)',
				width: 6,
				default: '',
			},
			{
				type: 'static-text',
				id: 'dummy3',
				width: 12,
				label: ' ',
				value: ' ',
			},
			{
				type: 'checkbox',
				id: 'enableTracking',
				label: 'Enable Auto Tracking Add-On Features',
				width: 3,
				default: false,
			},
			{
				type: 'textinput',
				id: 'trackingAddonUrl',
				label: 'Auto Tracking CGI Add-on URL',
				width: 12,
				default: '/cgi-addon/Auto_Tracking_RA-AT001/app_ctrl/',
				isVisible: (configValues) => configValues.enableTracking == true
			},
			{
				type: 'textinput',
				id: 'trackingInterval',
				label: 'Tracking Update Interval (how often to request latest tracking data)',
				width: 6,
				default: 250,
				isVisible: (configValues) => configValues.enableTracking == true
			},
			{
				type: 'static-text',
				id: 'Info',
				width: 12,
				label: 'Other Settings',
				value:
					'These setting can be left on the default values and should give you a consistent setup, but they are there for you to use if need be.',
			},
			{
				type: 'checkbox',
				id: 'verbose',
				width: 6,
				label: 'Verbose Mode',
				default: true,
			}
		]
	}
}
